name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cloud_firestore: ^4.9.1
  convex_bottom_bar: 3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_auth_mocks: ^0.12.0
  firebase_storage: ^11.2.6
  geolocator: ^10.0.1
  get: 4.6.5
  google_nav_bar: ^5.0.6
  image_picker: 1.0.4
  intl: 0.18.1
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: ^22.2.12
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter



flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.jpg
  ios: true

flutter: 
  uses-material-design: true
 

