name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_auth_mocks: ^0.12.0
  get: 4.6.5
  image_picker: 1.0.4
  firebase_storage: ^11.2.6
  convex_bottom_bar: 3.2.0
  google_nav_bar: ^5.0.6

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

