name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_auth_mocks: ^0.12.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
